##########################################
# Hitachi Content Platform Prometheus exporter for S Node
##########################################
# Port run exporter
port: 8000

# Host run in exporter
host: 0.0.0.0

# Enable debug logging for exporter
debug: false

# Default: /var/log/hitachi_S_series.log
log_file: "/var/log/hitachi_S_series.log"

# List monitoring S nodes
snodes:
  - node_name: "node1"
    base_url: "https://10.1.22.167:9090"
    Authorization: "Basic YWRtaW46U3RhcnQxMjMh"
  - node_name: "node2"
    base_url: "https://10.1.22.167:9090"
    Authorization: "Basic YWRtaW46U3RhcnQxMjMh"

endpoints:
  api1: "/mapi/system/status/full"
  api2: "/mapi/metrics/resourceLoad"
  api3: "/mapi/metrics/system"

metrics:
  - metric_name: "totalMemory"
    api_endpoint: api1
    metric_path: "/root/systemStatus/hardware/serverModuleInfo/item/coreHardware/totalMemory"
    labels:
      - label_name: "id"
        label_path: "ancestor::item/id"
  - metric_name: "usedMemory"
    api_endpoint: api1
    metric_path: "/root/systemStatus/hardware/serverModuleInfo/item/coreHardware/usedMemory"
    labels:
      - label_name: "id"
        label_path: "ancestor::item/id"
  - metric_name: "cpuUsagePercent"
    api_endpoint: api2
    metric_path: "/root/cpuUsagePercent"
    labels: []
  - metric_name: "freeNetworkBandwidth"
    api_endpoint: api2
    metric_path: "/root/freeNetworkBandwidth"
    labels: []
  - metric_name: "totalNetworkBandwidth"
    api_endpoint: api2
    metric_path: "/root/totalNetworkBandwidth"
    labels: []
  - metric_name: "totalBytes"
    api_endpoint: api3
    metric_path: "/root/totalBytes"
    labels: []
  - metric_name: "usedBytes"
    api_endpoint: api3
    metric_path: "/root/usedBytes"
    labels: []
  - metric_name: "freeBytes"
    api_endpoint: api3
    metric_path: "/root/freeBytes"
    labels: []
  - metric_name: "percentUsed"
    api_endpoint: api3
    metric_path: "/root/percentUsed"
    labels: []
  - metric_name: "bucketCount"
    api_endpoint: api3
    metric_path: "/root/bucketCount"
    labels: []
  - metric_name: "objectCount"
    api_endpoint: api3
    metric_path: "/root/objectCount"
    labels: []